DROP TABLE IF EXISTS `StockQuote`.`ABAN`;
 CREATE TABLE IF NOT EXISTS `StockQuote`.`ABAN` (
 `ID` bigint(20) NOT NULL AUTO_INCREMENT, 
 TradeDate datetime NOT NULL, 
 OpenPrice FLOAT(9,2) NOT NULL, 
 HighPrice FLOAT(9,2) NOT NULL, 
 LowPrice FLOAT(9,2) NOT NULL, 
 LastTradedPrice FLOAT(9,2) NOT NULL, 
 ClosePrice FLOAT(9,2) NOT NULL, 
 TotalTradedQuantity int NOT NULL, 
 Turnover FLOAT(9,2) NOT NULL,
 RSI FLOAT(9,2),
 ADL int, 
 SMA20Day FLOAT(9,2),
 SMA50Day FLOAT(9,2),
 SMA100Day FLOAT(9,2),
 SMA200Day FLOAT(9,2),
 CommodityChannelIndex FLOAT(9,2),
 DIPlus FLOAT(9,2),
 DIMinus FLOAT(9,2),
 ADX FLOAT(9,2),
 UpperBollgerBand FLOAT(9,2),
 LowerBollgerBand FLOAT(9,2),
 EMA3Day FLOAT(9,2),
 EMA15Day FLOAT(9,2),
 EMA5Day FLOAT(9,2),
 EMA20Day FLOAT(9,2),
 EMA12Day FLOAT(9,2),
 EMA9Day FLOAT(9,2),
 EMA26Day FLOAT(9,2),
 EMATrend VARCHAR(40),
 EMARecommendation VARCHAR(40),
 PRIMARY KEY (`ID`) 
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

